# Generated by Django 4.1.1 on 2022-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='purchaser',
            new_name='chef',
        ),
    ]
